api:
  dashboard: true
  insecure: true  

entryPoints:
  web:
    address: ":${PORT:-80}"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO


serversTransport:
  insecureSkipVerify: true  