api:
  dashboard: false


entryPoints:
  web:
    address: ":3000"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO


serversTransport:
  insecureSkipVerify: true  