name: publish_loadbalencer
on:
    [workflow_dispatch]
jobs:
  publish:
    name: publish server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./loadbalencer
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: login to DOCKER HUB
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKER_USER_NAME }}
            password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
        - name: build surver docker image
          run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/aeie_club_loadbalencer_:latest .
        - name: push server docker image
          run: docker push ${{ secrets.DOCKER_USER_NAME }}/aeie_club_loadbalencer_:latest     